---
- hosts:        all
  tasks:
    - name:     Test connection
      ping:
        
- hosts:        loadbalancer
  become:       yes
  roles:
    -           lb-tier

- hosts:        backend
  become:       yes
  roles:
    -           app-tier

- hosts:        database
  become:       yes
  roles:
    -           db-tier

# - hosts:        all
#   become:       yes
#   roles:
#     -           create-users